services:
  postgres:
    image: 'postgres:alpine'
    container_name: entregaDB
    environment:
      - 'POSTGRES_DB=entregaDB'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=sa'
    ports:
      - '5433:5432'
    networks:
      - app_network

  app:
      image: 'openjdk:17-jdk'
      container_name: entregaApp
      depends_on:
        - postgres
      environment:
        - 'SPRING_DATASOURCE_URL=jdbc:postgresql://entregaDB:5432/entregaDB'
        - 'SPRING_DATASOURCE_USERNAME=sa'
        - 'SPRING_DATASOURCE_PASSWORD=password'
      ports:
        - '8083:8083'
      volumes:
        - './target:/app'
      working_dir: /app
      command: [ "java", "-jar", "entrega-0.0.1-SNAPSHOT.jar" ]
      networks:
        - app_network

networks:
  app_network:
    external: true


