services:
  db:
    image: postgres:alpine
    container_name: "postgre_entrega_container"
    environment:
      POSTGRES_DB: "entregaDB"
      POSTGRES_USER: "sa"
      POSTGRES_PASSWORD: "password"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sa -d entregaDB"]
      interval: 15s
      timeout: 15s
      retries: 3

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java_app_container
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/entregaDB"
      SPRING_DATASOURCE_USERNAME: "sa"
      SPRING_DATASOURCE_PASSWORD: "password"
    ports:
      - "8083:8083"
    volumes:
      - app_data:/app/data

volumes:
  postgres_data:
  app_data: